USE  MESSENGER_SK
GO

CREATE TABLE USERS(
	ID INT IDENTITY PRIMARY KEY,
	USERNAME VARCHAR(100) NOT NULL,
	PASSW VARCHAR(50) NOT NULL,
	FULLNAME NVARCHAR(200) NOT NULL,
	EMAIL VARCHAR(200) NOT NULL,
	AVATAR VARCHAR(100) ,
	GENDER NVARCHAR(20)
	)
	SELECT * FROM USERS
	SELECT * FROM MESSAGERECIPIENTS
	SELECT * FROM MESSAGES
	SELECT * FROM MESSAGES RIGHT JOIN USERS ON USERS.ID = MESSAGES.IDSENDER JOIN MESSAGERECIPIENTS ON MESSAGES.IDMESSAGE = MESSAGERECIPIENTS.IDMESSAGE WHERE USERS.ID = 1 OR USERS.ID = 2 ORDER BY DATESEND ASC
	CREATE TABLE MESSAGES (
		IDMESSAGE INT IDENTITY PRIMARY KEY,
		IDSENDER INT FOREIGN KEY REFERENCES USERS(ID),
		DATESEND DATETIME,
		DATEREAD DATETIME,
		CONTENT NVARCHAR(MAX),
		TYPEMESS VARCHAR(20)
	)
	
	CREATE TABLE MESSAGERECIPIENTS(
		IDMESSAGE INT FOREIGN KEY REFERENCES MESSAGES(IDMESSAGE),
		IDRECIPIENT INT FOREIGN KEY REFERENCES USERS(ID),
		PRIMARY KEY (IDMESSAGE, IDRECIPIENT)
	)

INSERT INTO USERS VALUES( 'NAMNAM2303', '12345', N'NGUYỄN PHƯƠNG NAM', 'IMSOFH@GMAIL.COM', NULL, 'NAM')
INSERT INTO USERS VALUES( 'LONG123', '12345', N'VŨ TIẾN LONG', 'LONGVTTH18869@FPT.EDU.VN', NULL, 'NAM')
INSERT INTO MESSAGES VALUES( '1', GETDATE(), NULL, N'ĐANG LÀM GÌ ĐẤY BRO', NULL)
INSERT INTO MESSAGERECIPIENTS VALUES(1,2)
INSERT INTO MESSAGES VALUES( '2', GETDATE(), NULL, N'ĐANG NGHIÊN CỨU DỰ ÁN MẪU', 'TEXT')
INSERT INTO MESSAGERECIPIENTS VALUES(2,1)
INSERT INTO MESSAGES VALUES( '1', GETDATE(), NULL, N'LÀM TRẬN GAME ĐI', 'IMAGE')
INSERT INTO MESSAGERECIPIENTS VALUES(3,2)
GO
EXEC  GETDIALOGUE 'NAMNAM2303', 'LONG123'
ALTER PROC GETDIALOGUE @USER1 VARCHAR(50) , @USER2 VARCHAR(50)
AS
SELECT DATESEND, CONTENT, (SELECT USERNAME FROM USERS WHERE ID = IDSENDER)AS 'SENDER', (SELECT USERNAME FROM USERS WHERE ID = IDRECIPIENT)AS 'RECIPIENT' FROM MESSAGES JOIN USERS ON IDSENDER = (SELECT ID FROM USERS WHERE USERNAME = @USER1) OR IDSENDER = (SELECT ID FROM USERS WHERE USERNAME = @USER2)
JOIN MESSAGERECIPIENTS ON MESSAGES.IDMESSAGE = MESSAGERECIPIENTS.IDMESSAGE AND (IDRECIPIENT = (SELECT ID FROM USERS WHERE USERNAME = @USER1) OR IDRECIPIENT = (SELECT ID FROM USERS WHERE USERNAME = @USER2))
GROUP BY MESSAGES.IDMESSAGE, DATESEND, CONTENT,IDSENDER, IDRECIPIENT
ORDER BY DATESEND ASC

CREATE PROC ADDMESSAGE @CONTENT NVARCHAR(MAX), @SENDER VARCHAR(100), @RECIPIENT VARCHAR(100)
AS
INSERT	INTO MESSAGES VALUES ((SELECT ID FROM USERS WHERE USERNAME = @SENDER), GETDATE(), NULL, @CONTENT, NULL)
INSERT INTO MESSAGERECIPIENTS VALUES ( (SELECT MAX(IDMESSAGE) FROM MESSAGES),( SELECT ID FROM USERS WHERE USERNAME = @RECIPIENT))

